<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-02-16 14:05

from django.db import migrations, models
=======
# Generated by Django 4.0.1 on 2022-02-15 22:40

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> a3c41a7 (Add: Initial Models)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250, null=True)),
                ('has_agreed', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('kakao_id', models.PositiveIntegerField()),
=======
>>>>>>> a3c41a7 (Add: Initial Models)
            ],
            options={
                'db_table': 'users',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_platform_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'socials',
            },
        ),
>>>>>>> a3c41a7 (Add: Initial Models)
    ]
