# Generated by Django 4.0.1 on 2022-02-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_platform_name',
        ),
    ]
