# Generated by Django 4.0.1 on 2022-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='detail_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(),
        ),
    ]
