# Generated by Django 4.0.1 on 2022-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_detail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='check_in_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='check_out_date',
            field=models.DateTimeField(null=True),
        ),
    ]
