# Generated by Django 4.0.1 on 2022-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accommodation_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'main_page_videos',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='available_people',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(blank=True),
        ),
    ]
